
language: ruby

services:
  - mysql

before_install:
  - mysql -e 'create database myapp_test;' -u root -p
  - root

script:
  - bundle exec spring binstub --all
  - bundle install
  - bundle exec rake db:load_config
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake spec

rvm:
  - 2.3.1

notifications:
  email:
    recipients:
      - gesiel.was.f@gmail.com
      - vitorbertulucci@hotmail.com
branches:
  only:
    - master
