
language: ruby

services:
  - mysql

before_install: 
  - mysql -e 'create database myapp_test;' -uroot

script:
  - bundle exec spring binstub --all
  - bundle install
  - bundle exec rake db:load_config
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake spec

rvm:
  - 2.2.3

notifications:
  email:
    recipients:
      - gesiel.was.f@gmail.com
      - vitorbertulucci@hotmail.com
branches:
  only:       
  

