default: &default
    adapter: mysql2
    username: root	
    encoding: utf8
    pool: 5
    timeout: 5000

development:
    <<: *default
    database: avalia_mais_development
    password: root	

test: &test
    database: avalia_mais_test
    adapter: mysql2
    username: teste	
    encoding: utf8
    pool: 5
    timeout: 5000

production:
    <<: *default
    database: avalia_mais_production

cucumber:
  <<: *test
