development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: avalia_mais_development
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  database: myapp_test
  username: travis
  encoding: utf8

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: avalia_mais_production
  pool: 5
  username: root
  password: root
  host: localhost





cucumber:
  <<: *test
