default: &default
    adapter: mysql2
    username: bfbf9a1efd87f8
    encoding: utf8
    pool: 5
    timeout: 5000

development:
    <<: *default
    database: avalia_mais_development
    password: root	

test: &test
    <<: *default
    database: avalia_mais_test
    

production:
    <<: *default
    host: us-cdbr-iron-east-03.cleardb.net
    database: heroku_0eed1d02dde2e3b
    password: 990d5abd


cucumber:
  <<: *test
